const products = [
  {
    name: "Woman's Hiking Jacket",
    image: "/images/woman-hiking.png",
    id: 1,
    price: 999,
    product_code: "#457782625",
    description:
      "The Woman's Hiking Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    category: "woman",
  },
  {
    name: "Woman's Cycling Jacket",
    image: "/images/woman-cycling.png",
    id: 2,
    price: 799,
    product_code: "#457782625",
    description:
      "The Woman's Cycling Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    category: "woman",
  },
  {
    name: "Woman's Hunter Jacket",
    image: "/images/woman-hunter.png",
    id: 3,
    price: 999,
    product_code: "#457782625",
    description:
      "The Woman's Hunter Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    category: "woman",
  },
  {
    name: "Woman's Jacket",
    image: "/images/woman.png",
    id: 4,
    price: 999,
    product_code: "#457782625",
    description:
      "The Woman's Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    category: "woman",
  },
  {
    name: "Woman's Rain Jacket",
    image: "/images/woman-hiking.png",
    id: 5,
    price: 999,
    product_code: "#457782625",
    description:
      "The Woman's Rain Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    category: "woman",
  },
  {
    name: "Woman's Skiing Jacket",
    image: "/images/woman-skiing.png",
    id: 6,
    price: 1499,
    product_code: "#092882625",
    description:
      "The Woman's Skiing Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: true,
    sale_nr: "40 %",
    rating: "&#11088; &#11088; &#11088; &#11088;",
    category: "woman",
  },
  {
    name: "Woman's Canoeing Jacket",
    image: "/images/woman-canoeing.png",
    id: 7,
    price: 1199,
    product_code: "#772882625",
    product_code: "#898826s25",
    description:
      "The Woman's Canoeing Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088;",
    category: "woman",
  },
  {
    name: "Woman's Camping Jacket",
    image: "/images/woman-camping.png",
    id: 8,
    price: 1999,
    product_code: "#767882625",
    description:
      "The Woman's Camping Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088;",
    category: "woman",
  },

  {
    name: "Man's Hiking Jacket",
    image: "/images/man-hiking.png",
    id: 9,
    price: 1699,
    product_code: "#889882625",
    description:
      "The Man's Hiking Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    category: "man",
  },
  {
    name: "Man's Hunter Jacket",
    image: "/images/man-hunter.png",
    id: 10,
    price: 1699,
    product_code: "#889882625",
    description:
      "The Man's Hunter Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    category: "man",
  },
  {
    name: "Man's Cycling Jacket",
    image: "/images/man-cycling.png",
    id: 11,
    price: 1699,
    product_code: "#889882625",
    description:
      "The Man's Cycling Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    category: "man",
  },
  {
    name: "Man's Skiing Jacket",
    image: "/images/man-skiing.png",
    id: 12,
    price: 700,
    product_code: "#782882625",
    description:
      "The Man's Skiing Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: true,
    sale_nr: "60 %",
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    category: "man",
  },
  {
    name: "Man's Canoeing Jacket",
    image: "/images/man-canoeing.png",
    id: 13,
    price: 1700,
    product_code: "#777782625",
    description:
      "The Man's Canoeing Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: true,
    sale_nr: "70 %",
    rating: "&#11088; &#11088; &#11088; &#11088;",
    category: "man",
  },
  {
    name: "Man's Camping Jacket",
    image: "/images/man-camping.png",
    id: 14,
    price: 1599,
    product_code: "#234882625",
    description:
      "The Man's Camping Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    category: "man",
  },
  {
    name: "Man's Rain Jacket",
    image: "/images/man-rain.png",
    id: 15,
    price: 1599,
    product_code: "#234882625",
    description:
      "The Man's Rain Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    category: "man",
  },
  {
    name: "Man's Jacket",
    image: "/images/man.png",
    id: 16,
    price: 1599,
    product_code: "#234882625",
    description:
      "The Man's Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    category: "man",
  },

  {
    name: "Kid's Hiking Jacket",
    image: "/images/kid-hiking.png",
    id: 17,
    price: 899,
    product_code: "#972882625",
    description:
      "The Kid's Hiking Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: true,
    sale_nr: "50 %",
    rating: "&#11088; &#11088; &#11088; &#11088;",
    category: "kid",
  },

  {
    name: "Kid's Skiing Jacket",
    image: "/images/kid-skiing.png",
    id: 18,
    price: 1100,
    product_code: "#8982625",
    description:
      "The Kid's Skiing Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    category: "kid",
  },
  {
    name: "Kid's Canoeing Jacket",
    image: "/images/kid-canoeing.png",
    id: 19,
    price: 399,
    product_code: "#772882625",
    description:
      "The Kid's Canoeing Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088;",
    category: "kid",
  },
  {
    name: "Kid's Camping Jacket",
    image: "/images/kid-camping.png",
    id: 20,
    price: 399,
    product_code: "#8s8882625",
    description:
      "The Kid's Camping Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    category: "kid",
  },
];
