const products = [
  {
    name: "Woman's Hiking Jacket",
    image: "/RainyDays/images/woman-hiking.png",
    id: 1,
    price: 999,
    product_code: "#457782625",
    description:
      "The Woman's Hiking Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    categorie: "Woman",
  },
  {
    name: "Woman's Skiing Jacket",
    image: "/RainyDays/images/woman-skiing.png",
    id: 2,
    price: 1499,
    product_code: "#092882625",
    description:
      "The Woman's Skiing Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: true,
    rating: "&#11088; &#11088; &#11088; &#11088;",
    categorie: "Woman",
  },
  {
    name: "Woman's Canoeing Jacket",
    image: "/RainyDays/images/woman-canoeing.png",
    id: 3,
    price: 1199,
    product_code: "#772882625",
    product_code: "#898826s25",
    description:
      "The Woman's Canoeing Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088;",
    categorie: "Woman",
  },
  {
    name: "Woman's Camping Jacket",
    image: "/RainyDays/images/woman-camping.png",
    id: 4,
    price: 1999,
    product_code: "#767882625",
    description:
      "The Woman's Camping Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088;",
    categorie: "Woman",
  },

  {
    name: "Man's Hiking Jacket",
    image: "/RainyDays/images/man-hiking.png",
    id: 5,
    price: 1699,
    product_code: "#889882625",
    description:
      "The Man's Hiking Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    categorie: "Man",
  },
  {
    name: "Man's Skiing Jacket",
    image: "/RainyDays/images/man-skiing.png",
    id: 6,
    price: 700,
    product_code: "#782882625",
    description:
      "The Man's Skiing Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: true,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    categorie: "Man",
  },
  {
    name: "Man's Canoeing Jacket",
    image: "/RainyDays/images/man-canoeing.png",
    id: 7,
    price: 1700,
    product_code: "#777782625",
    description:
      "The Man's Canoeing Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: true,
    rating: "&#11088; &#11088; &#11088; &#11088;",
    categorie: "Man",
  },
  {
    name: "Man's Camping Jacket",
    image: "/RainyDays/images/man-camping.png",
    id: 8,
    price: 1599,
    product_code: "#234882625",
    description:
      "The Man's Camping Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    categorie: "Man",
  },

  {
    name: "Kid's Hiking Jacket",
    image: "/RainyDays/images/kid-hiking.png",
    id: 9,
    price: 899,
    product_code: "#972882625",
    description:
      "The Kid's Hiking Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: true,
    rating: "&#11088; &#11088; &#11088; &#11088;",
    categorie: "Kid",
  },
  {
    name: "Kid's Skiing Jacket",
    image: "/RainyDays/images/kid-skiing.png",
    id: 10,
    price: 1100,
    product_code: "#8982625",
    description:
      "The Kid's Skiing Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    categorie: "Kid",
  },
  {
    name: "Kid's Canoeing Jacket",
    image: "/RainyDays/images/kid-canoeing.png",
    id: 11,
    price: 399,
    product_code: "#772882625",
    description:
      "The Kid's Canoeing Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088;",
    categorie: "Kid",
  },
  {
    name: "Kid's Camping Jacket",
    image: "/RainyDays/images/kid-camping.png",
    id: 12,
    price: 399,
    product_code: "#8s8882625",
    description:
      "The Kid's Camping Jacket is a Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    size: ["S", "M", "L", "XL"],
    sale: false,
    rating: "&#11088; &#11088; &#11088; &#11088; &#11088;",
    categorie: "Kid",
  },
];
